[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://your-laravel-backend.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"